# Generated by Django 4.0.6 on 2022-10-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_ros_api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveRuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=200)),
                ('sum_type_id', models.IntegerField()),
                ('config_id', models.IntegerField()),
            ],
        ),
    ]
