# Generated by Django 4.0.6 on 2022-08-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_ros_api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuMType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
